CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210713125134_DbInitMessageCenter') THEN
    CREATE TABLE "Message" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "MessageTypeId" integer NOT NULL,
        "Title" character varying(256) NULL,
        "Description" character varying(512) NULL,
        "Data" json NULL,
        "ReadState" boolean NOT NULL,
        "DeliveryState" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreateTime" timestamp without time zone NOT NULL,
        "ReadTime" timestamp without time zone NOT NULL,
        "DeleteTime" timestamp without time zone NOT NULL,
        "ExpirationTime" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Message" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210713125134_DbInitMessageCenter') THEN
    CREATE TABLE "Message_Push_Platform" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NULL,
        "Description" character varying(512) NULL,
        "ProviderName" character varying(256) NULL,
        "Config" json NULL,
        "Priority" integer NOT NULL,
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_Message_Push_Platform" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210713125134_DbInitMessageCenter') THEN
    CREATE TABLE "Message_Push_Record" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "MessageId" bigint NOT NULL,
        "PlatformId" integer NOT NULL,
        "Content" text NULL,
        "Url" text NULL,
        "PushState" boolean NOT NULL,
        "RetriesNum" integer NOT NULL,
        "Remark" text NULL,
        CONSTRAINT "PK_Message_Push_Record" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210713125134_DbInitMessageCenter') THEN
    CREATE TABLE "Message_Session" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "MessageTypeId" integer NOT NULL,
        "Title" character varying(256) NULL,
        "Description" character varying(512) NULL,
        "Data" json NULL,
        "UserIds" json NULL,
        "UserNum" integer NOT NULL,
        "PushNum" integer NOT NULL,
        "CreateTime" timestamp without time zone NOT NULL,
        "State" integer NOT NULL,
        "CompleteTime" timestamp without time zone NOT NULL,
        "ExpirationTime" timestamp without time zone NOT NULL,
        "Remark" text NULL,
        CONSTRAINT "PK_Message_Session" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210713125134_DbInitMessageCenter') THEN
    CREATE TABLE "Message_Template" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PlatformId" integer NOT NULL,
        "MessageTypeCode" character varying(256) NULL,
        "Name" character varying(256) NULL,
        "Description" character varying(512) NULL,
        "TemplateCode" character varying(256) NULL,
        "ContentTemplate" character varying(512) NULL,
        "UrlTemplate" character varying(512) NULL,
        CONSTRAINT "PK_Message_Template" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210713125134_DbInitMessageCenter') THEN
    CREATE TABLE "Message_Type" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NULL,
        "Code" character varying(256) NULL,
        "Icon" character varying(256) NULL,
        "TitleTemplate" character varying(512) NULL,
        "DescriptionTemplate" character varying(512) NULL,
        "Schema" text NULL,
        "PushStrategy" integer NOT NULL,
        "PushPlatform" json NULL,
        "ValidDays" integer NOT NULL,
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_Message_Type" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210713125134_DbInitMessageCenter') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210713125134_DbInitMessageCenter', '5.0.7');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210719063613_AddTopic') THEN
    ALTER TABLE "Message_Type" RENAME COLUMN "Icon" TO "Topic";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210719063613_AddTopic') THEN
    ALTER TABLE "Message" ADD "SessionId" bigint NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210719063613_AddTopic') THEN
    CREATE TABLE "Message_Topic" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NULL,
        "Code" character varying(256) NULL,
        "Icon" character varying(512) NULL,
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_Message_Topic" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210719063613_AddTopic') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210719063613_AddTopic', '5.0.7');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210720092237_AddPlatformCode') THEN
    ALTER TABLE "Message_Push_Platform" ALTER COLUMN "Id" TYPE integer;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210720092237_AddPlatformCode') THEN
    ALTER TABLE "Message_Push_Platform" ADD "Code" character varying(256) NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210720092237_AddPlatformCode') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210720092237_AddPlatformCode', '5.0.7');
    END IF;
END $$;
COMMIT;

