CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE TABLE "Identity_Roles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NULL,
        "NormalizedName" character varying(256) NULL,
        "ConcurrencyStamp" character varying(256) NULL,
        "Description" character varying(1024) NULL,
        CONSTRAINT "PK_Identity_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE TABLE "Identity_UserKeys" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "KeyId" character varying(64) NULL,
        "PublicKey" character varying(1024) NULL,
        "SignatureRule" character varying(256) NULL,
        "SignatureData" character varying(1024) NULL,
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_Identity_UserKeys" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE TABLE "Identity_Users" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "NickName" character varying(256) NULL,
        "RealName" character varying(256) NULL,
        "Sex" character varying(1) NULL,
        "Birthday" timestamp with time zone NOT NULL,
        "IsReal" boolean NOT NULL,
        "ProfilePicture" character varying(1024) NULL,
        "SecurityStamp" character varying(256) NULL,
        "ConcurrencyStamp" character varying(256) NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        "LockoutEnd" timestamp with time zone NULL,
        "LockoutEnabled" boolean NULL,
        "UserName" character varying(256) NULL,
        "NormalizedUserName" character varying(256) NULL,
        "PasswordHash" character varying(1024) NULL,
        "PhoneNumber" character varying(64) NULL,
        "PhoneNumberConfirmed" boolean NULL,
        "Email" character varying(256) NULL,
        "NormalizedEmail" character varying(256) NULL,
        "EmailConfirmed" boolean NULL,
        "Ethnicity" character varying(32) NULL,
        "Address" character varying(256) NULL,
        "IDNumber" character varying(32) NULL,
        "IssuingAuthority" character varying(64) NULL,
        "StartDate" timestamp with time zone NULL,
        "EndDate" timestamp with time zone NULL,
        "Photo" text NULL,
        "Fingerprint" text NULL,
        "FeatureCode" text NULL,
        "CreatorId" bigint NOT NULL,
        "Creator" character varying(256) NULL,
        "CreationTime" timestamp without time zone NULL,
        "LastModifierId" bigint NOT NULL,
        "Modifier" character varying(256) NULL,
        "LastModificationTime" timestamp without time zone NULL,
        "IsEnabled" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Identity_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE TABLE "Identity_RoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" integer NOT NULL,
        "ClaimType" character varying(256) NULL,
        "ClaimValue" character varying(256) NULL,
        CONSTRAINT "PK_Identity_RoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Identity_RoleClaims_Identity_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Identity_Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE TABLE "Identity_UserClaims" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "ClaimType" character varying(256) NULL,
        "ClaimValue" character varying(256) NULL,
        CONSTRAINT "PK_Identity_UserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Identity_UserClaims_Identity_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Identity_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE TABLE "Identity_UserFingerprints" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "FingerName" character varying(64) NULL,
        "Fingerprint" character varying(1024) NULL,
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_Identity_UserFingerprints" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Identity_UserFingerprints_Identity_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Identity_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE TABLE "Identity_UserLogins" (
        "_loginProvider" text NOT NULL,
        "_providerKey" text NOT NULL,
        "ProviderDisplayName" character varying(256) NULL,
        "UserId" bigint NOT NULL,
        CONSTRAINT "PK_Identity_UserLogins" PRIMARY KEY ("_loginProvider", "_providerKey"),
        CONSTRAINT "FK_Identity_UserLogins_Identity_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Identity_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE TABLE "Identity_UserRoles" (
        "UserId" bigint NOT NULL,
        "RoleId" integer NOT NULL,
        "UserRole_UserId" bigint NOT NULL,
        CONSTRAINT "PK_Identity_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_Identity_UserRoles_Identity_Users_UserRole_UserId" FOREIGN KEY ("UserRole_UserId") REFERENCES "Identity_Users" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Identity_UserRoles_Identity_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Identity_Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE TABLE "Identity_UserTokens" (
        "UserId" bigint NOT NULL,
        "_loginProvider" text NOT NULL,
        _name text NOT NULL,
        "Value" character varying(256) NULL,
        "UserToken_UserId" bigint NOT NULL,
        CONSTRAINT "PK_Identity_UserTokens" PRIMARY KEY ("UserId", "_loginProvider", _name),
        CONSTRAINT "FK_Identity_UserTokens_Identity_Users_UserToken_UserId" FOREIGN KEY ("UserToken_UserId") REFERENCES "Identity_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE INDEX "IX_Identity_RoleClaims_RoleId" ON "Identity_RoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "Identity_Roles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE INDEX "IX_Identity_UserClaims_UserId" ON "Identity_UserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE INDEX "IX_Identity_UserFingerprints_UserId" ON "Identity_UserFingerprints" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE INDEX "IX_Identity_UserLogins_UserId" ON "Identity_UserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE INDEX "IX_Identity_UserRoles_UserRole_UserId" ON "Identity_UserRoles" ("UserRole_UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE INDEX "IX_Identity_UserRoles_RoleId" ON "Identity_UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "Identity_Users" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE INDEX "EmailIndex" ON "Identity_Users" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    CREATE INDEX "IX_Identity_UserTokens_UserToken_UserId" ON "Identity_UserTokens" ("UserToken_UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200401021641_InitialIdentity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200401021641_InitialIdentity', '6.0.1');
    END IF;
END $EF$;
COMMIT;

