CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210708084612_InitialMessageCenter') THEN
    CREATE TABLE "Message" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "MessageTypeId" integer NOT NULL,
        "Title" character varying(256) NULL,
        "Description" character varying(512) NULL,
        "Data" text NULL,
        "ReadState" boolean NOT NULL,
        "DeliveryState" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreateTime" timestamp without time zone NOT NULL,
        "ReadTime" timestamp without time zone NOT NULL,
        "DeleteTime" timestamp without time zone NOT NULL,
        "ExpirationTime" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Message" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210708084612_InitialMessageCenter') THEN
    CREATE TABLE "Message_MessageType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NULL,
        "Code" character varying(256) NULL,
        "Icon" character varying(256) NULL,
        "TitleTemplate" character varying(512) NULL,
        "DescriptionTemplate" character varying(512) NULL,
        "Schema" text NULL,
        "PushStrategy" integer NOT NULL,
        "PushPlatform" character varying(512) NULL,
        "ValidDays" integer NOT NULL,
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_Message_MessageType" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210708084612_InitialMessageCenter') THEN
    CREATE TABLE "Message_PushPlatform" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NULL,
        "Description" character varying(512) NULL,
        "ProviderName" character varying(256) NULL,
        "Config" text NULL,
        "Priority" integer NOT NULL,
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_Message_PushPlatform" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210708084612_InitialMessageCenter') THEN
    CREATE TABLE "Message_PushRecord" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "MessageId" bigint NOT NULL,
        "PlatformId" integer NOT NULL,
        "Content" text NULL,
        "Url" text NULL,
        "PushState" boolean NOT NULL,
        "RetriesNum" integer NOT NULL,
        "Remark" text NULL,
        CONSTRAINT "PK_Message_PushRecord" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210708084612_InitialMessageCenter') THEN
    CREATE TABLE "Message_Session" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "MessageTypeId" integer NOT NULL,
        "Title" character varying(256) NULL,
        "Description" character varying(512) NULL,
        "Data" text NULL,
        "UserIds" text NULL,
        "UserNum" integer NOT NULL,
        "PushNum" integer NOT NULL,
        "CreateTime" timestamp without time zone NOT NULL,
        "State" integer NOT NULL,
        "CompleteTime" timestamp without time zone NOT NULL,
        "ExpirationTime" timestamp without time zone NOT NULL,
        "Remark" text NULL,
        CONSTRAINT "PK_Message_Session" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210708084612_InitialMessageCenter') THEN
    CREATE TABLE "Message_Template" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PlatformId" integer NOT NULL,
        "MessageTypeCode" character varying(256) NULL,
        "Name" character varying(256) NULL,
        "Description" character varying(512) NULL,
        "TemplateCode" character varying(256) NULL,
        "ContentTemplate" character varying(512) NULL,
        "UrlTemplate" character varying(512) NULL,
        CONSTRAINT "PK_Message_Template" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210708084612_InitialMessageCenter') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210708084612_InitialMessageCenter', '5.0.7');
    END IF;
END $$;
COMMIT;

